// <auto-generated />
using System;
using BulgarianTraditionsAndCustoms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulgarianTraditionsAndCustoms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251229134144_CreateTradtionsParticipantsTable")]
    partial class CreateTradtionsParticipantsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulgarianTraditionsAndCustoms.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("BulgarianTraditionsAndCustoms.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("BulgarianTraditionsAndCustoms.Models.Tradition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CelebrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("TraditionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("TraditionTypeId");

                    b.ToTable("Traditions");
                });

            modelBuilder.Entity("BulgarianTraditionsAndCustoms.Models.TraditionParticipant", b =>
                {
                    b.Property<int>("TraditionId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<string>("ParticipantRole")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TraditionId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("TraditionsParticipants");
                });

            modelBuilder.Entity("BulgarianTraditionsAndCustoms.Models.TraditionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TraditionTypes");
                });

            modelBuilder.Entity("BulgarianTraditionsAndCustoms.Models.Tradition", b =>
                {
                    b.HasOne("BulgarianTraditionsAndCustoms.Models.Region", "Region")
                        .WithMany("Traditions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BulgarianTraditionsAndCustoms.Models.TraditionType", "TraditionType")
                        .WithMany("Traditions")
                        .HasForeignKey("TraditionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("TraditionType");
                });

            modelBuilder.Entity("BulgarianTraditionsAndCustoms.Models.TraditionParticipant", b =>
                {
                    b.HasOne("BulgarianTraditionsAndCustoms.Models.Participant", "Participant")
                        .WithMany("TraditionParticipants")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BulgarianTraditionsAndCustoms.Models.Tradition", "Tradition")
                        .WithMany("TraditionParticipants")
                        .HasForeignKey("TraditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Tradition");
                });

            modelBuilder.Entity("BulgarianTraditionsAndCustoms.Models.Participant", b =>
                {
                    b.Navigation("TraditionParticipants");
                });

            modelBuilder.Entity("BulgarianTraditionsAndCustoms.Models.Region", b =>
                {
                    b.Navigation("Traditions");
                });

            modelBuilder.Entity("BulgarianTraditionsAndCustoms.Models.Tradition", b =>
                {
                    b.Navigation("TraditionParticipants");
                });

            modelBuilder.Entity("BulgarianTraditionsAndCustoms.Models.TraditionType", b =>
                {
                    b.Navigation("Traditions");
                });
#pragma warning restore 612, 618
        }
    }
}
